## AdaBoostClassifier   Adaptive Boosting
## which is a boosting algorithm

Why Is It Called Adaptive Boosting?

Because:

It adapts to the mistakes of previous models
Misclassified samples get higher weights
New models focus more on difficult samples

So each next model becomes a little stronger.

In [14]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification   # A function to generate synthetic (fake) classification data for testing
X, y = make_classification(n_samples=1000,  # 1000 rows (data points)
                           n_features=4,    # Each sample has 4 features
                           n_informative=2, # Only 2 features actually matter
                           n_redundant=0,   # No unnecessary duplicated features
                           random_state=0,  # For reproducibility
                           shuffle=False)

In [15]:
X

array([[-1.66853167, -1.29901346,  0.2746472 , -0.60362044],
       [-2.9728827 , -1.08878294,  0.70885958,  0.42281857],
       [-0.59614125, -1.37007001, -3.11685659,  0.64445203],
       ...,
       [ 0.91711204,  1.10596645,  0.86766522, -2.25625012],
       [ 0.10027664,  1.45875846, -0.44360274, -0.67002328],
       [ 1.0415229 , -0.01987143,  0.15216419, -1.9405334 ]],
      shape=(1000, 4))

In [16]:
X.shape

(1000, 4)

In [17]:
clf = AdaBoostClassifier(n_estimators=100, # means 100 weak learners (decision stumps)
                         random_state=0)   # makes results same every run
clf.fit(X,y)

,estimator,None
,n_estimators,100
,learning_rate,1.0
,algorithm,'deprecated'
,random_state,0


In [18]:
clf.predict([[0,0,0,0]])  #single value prediction

array([1])

In [19]:
clf.score(X,y)    #Returns accuracy score on the training data.

0.96

## Gradient Boosting

In [20]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score


In [21]:
# Create a Dataset
X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=5,
    random_state=42
)
# Creates a fake dataset with 1,000 rows & 10 features.

In [22]:
# Split into Training & Testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [15]:
# Train Gradient Boosting Model
model = GradientBoostingClassifier(
    n_estimators=100,       # number of trees to add # number of boosting rounds  
    learning_rate=0.1,   #how much each tree contributes
    max_depth=3,         # depth of each weak learner
    random_state=42
)

model.fit(X_train, y_train)


,loss,'log_loss'
,learning_rate,0.1
,n_estimators,100
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,3
,min_impurity_decrease,0.0
,init,None


In [16]:
# Make Predictions
y_pred = model.predict(X_test)


In [18]:
# Evaluate Accuracy
accuracy = accuracy_score(y_test, y_pred)


In [19]:
accuracy

0.96

## Bagging

## builds multiple models in parallel and then combines them to improve accuracy and reduce overfitting.

In [23]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier   #creates multiple SVC models.
from sklearn.datasets import make_classification #creates fake dataset for practice


In [24]:
X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)

In [26]:
X

array([[ 4.22341441e-01, -2.05321581e+00,  9.10178908e-01,
         3.17218215e-01],
       [-1.25732069e+00, -3.19826339e+00,  7.86327962e-01,
        -4.66419097e-01],
       [ 1.23195055e+00, -9.95105317e-01, -9.44446256e-01,
        -4.10049693e-01],
       [-4.37843295e-02, -1.27395967e+00, -1.70204139e-02,
         3.79151736e-01],
       [-1.30819171e+00, -1.28532883e+00,  2.25930895e+00,
        -4.22571517e-02],
       [-1.62073375e+00, -2.22244349e+00, -9.55945000e-01,
        -3.45981776e-01],
       [-3.59967304e-01, -1.41363563e+00, -4.63595975e-01,
         4.81481474e-01],
       [-7.62884416e-01, -1.45125944e+00, -1.54079701e+00,
         6.32619942e-02],
       [ 4.86681188e-01, -1.45709006e+00,  1.56506538e-01,
         2.32181036e-01],
       [-2.68051210e-01, -4.47369310e-01, -5.97316069e-01,
        -2.37921730e-01],
       [-3.69743600e+00, -4.61220130e-01, -1.42406091e+00,
        -4.93319883e-01],
       [ 1.83324682e-01, -7.66054695e-01, -5.42861476e-01,
      

In [27]:
X.shape

(100, 4)

In [28]:
y.shape

(100,)

In [29]:
clf = BaggingClassifier(estimator=SVC(),
                        n_estimators=10,   #Creates 10 different SVC models (base learners). 
                        random_state=0).fit(X, y)

In [30]:
clf.score(X,y)

0.92

In [31]:
clf.predict([[0, 0, 0, 0]])

array([1])

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
clf2= RandomForestClassifier(n_estimators=100, max_depth=4, random_state=0)
clf2.fit(X,y)
clf2.score(X,y)

0.98

In [34]:
from sklearn.ensemble import ExtraTreesClassifier
clf3=ExtraTreesClassifier(n_estimators=50,max_depth=8,random_state=0)
clf3.fit(X,y)
clf3.score(X,y)

0.99

In [35]:
import numpy as np
from sklearn.linear_model import LogisticRegression     #model 1
from sklearn.naive_bayes import GaussianNB              # Naive Bayes model (Model 2)
from sklearn.ensemble import RandomForestClassifier, VotingClassifier   # model 3  , Combines multiple models into one final model.

In [52]:
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
clf3 = GaussianNB()

# x= features, y= class labels
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
y = np.array([1, 1, 1, 2, 2, 2])

In [53]:
eclf1 = VotingClassifier(estimators=[
        ('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [54]:
eclf1 = eclf1.fit(X, y)

In [55]:
print(eclf1.predict(X))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1]


In [56]:
print(eclf1.score(X,y))

0.93


In [58]:
from sklearn.ensemble import StackingClassifier

In [61]:
estimators = [
    ('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
    ('svr', SVC(random_state=42))
]


In [63]:
clf = StackingClassifier(
    estimators=estimators, final_estimator=LogisticRegression())

In [64]:
clf.fit(X,y)

,estimators,"[('rf', ...), ('svr', ...)]"
,final_estimator,LogisticRegression()
,cv,None
,stack_method,'auto'
,n_jobs,None
,passthrough,False
,verbose,0
,n_estimators,10
,criterion,'gini'
,max_depth,None
,min_samples_split,2


In [65]:
clf.score(X,y)

0.95